clean:
	./scripts/clean.sh
.PHONY: clean

mod-tidy:
	./scripts/mod-tidy.sh
.PHONY: mod-tidy

build:
	./scripts/build.sh
.PHONY: build

build-clean: clean build
.PHONY: build-clean

test:
	./scripts/test.sh
.PHONY: test
