name: Build And Publish Docker Image
on:
  push:
    branches:
      - main
jobs:
  main:
    runs-on: ubuntu-latest
    concurrency:
      cancel-in-progress: false
      group: ${{ format('{0}-{1}', github.event_name, github.ref_name) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Get Current Date Time
        id: date
        run: echo "::set-output name=date::$(date -u --iso-8601=seconds)"
      - name: Docker Meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: |
            ghcr.io/${{ github.repository }}
          tags: |
            type=edge
          labels: |
            maintainer=xeptore
            org.opencontainers.image.authors=xeptore
            org.opencontainers.image.version=${{ github.ref_name }}
            org.opencontainers.image.title=wgmngr
            org.opencontainers.image.url=githun
            maintainer='xeptore < hello [ at ] xeptore [ dot ] me >'
            org.opencontainers.image.created=${{ steps.date.outputs.date }}
            org.opencontainers.image.revision=${{ github.sha }}
          flavor: |
            latest=true
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v2
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          platforms: linux/amd64
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        id: docker_build_and_push
        uses: docker/build-push-action@v3
        with:
          push: true
          pull: true
          context: wgmngr
          file: wgmngr/Dockerfile
          no-cache: true
          tags: |
            ghcr.io/xeptore/wireguard-manager:latest
          labels: ${{ steps.meta.outputs.labels }}
        timeout-minutes: 10
